parameters:
#    molbi_vplg_web.example.class: Molbi\VPLGWebBundle\Example

services:
#    molbi_vplg_web.example:
#        class: %molbi_vplg_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
